---
abstract: 'Currying of subroutines via a new ''curry' declarator'
author:
  - osfameron
build_requires:
  Test::Exception: 0.00
  Test::More: 0.42
  Test::NoWarnings: 0.00
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Curried
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  B::Hooks::EndOfScope: 0.00
  Carp: 0.00
  Devel::BeginLift: 0.00
  Devel::Declare: 0.002000
  Sub::Current: 0.00
  Sub::Name: 0.00
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
